### ISSUE TITLE
#import "RCTBridgeModule.h" file not found

### ISSUE THREAD

**Issue by adrianotadao** [alinz/react-native-share-extension#22]
I'm receiving this error. What went wrong?

Take a look how is my `Header Search Paths`. It's a strange error because on my friend's computer it's working well.

![f_j052d5](https://cloud.githubusercontent.com/assets/387138/21808749/c72de468-d72b-11e6-9a42-466c0cebddf6.png)

Thank you.

**Comment by alinz** [comment]
@adrianotadao did you upgrade to React-native 0.40? if so you need to follow up with this issue
https://github.com/facebook/react-native/issues/11721#issuecomment-270672904

**Comment by adrianotadao** [comment]
@alinz I'm using the version `0.39.0`. The error just disappears. There are a bunch of things on XCode that I want to understand. Someday, who knows?!

I tried to update the react-native version but I'm using other libs that conflict with the version `0.40`. 

Now, everything here is okay and I don't know how I fixed.

Thank you a lot!

**Comment by alinz** [comment]
@adrianotadao what I usually do is slowly added each module and try to see if I can compile and run, and then I move to the next one. It is painful but this is how you should do it.

**Comment by adrianotadao** [comment]
@alinz yes, you're right but, React Native is a bit strange. This error has disappeared, now, it returns after I deleted the `ios/build`. This is going to drive me crazy.. =(

**Comment by njt1982** [comment]
@adrianotadao same here - how did you resolve?

**Comment by alinz** [comment]
@njt1982 I have been using this module with  react-native 0.45 without any issues. Please read the doc and follow the instruction. Pretty sure you missed something in there. Also, start with a plain simple project and try to get it to work.

**Comment by njt1982** [comment]
I had the same issue as @adrianotadao - turns out you seem to need to compile the main target first?!

(I have followed the instructions).

**Comment by adrianotadao** [comment]
@njt1982 I need to confess that I don't like so much React Native. Every single update that Xcode had, we had problems with the app. That's incredible!

About the error, I saw a lot of blog posts talking about the order on header search path. I changed everything and nothing had worked.

The bad news is that I don't know how I did the error disappear. In many of many times, the problem was with the update of Xcode but I don't know if is your case.

**Comment by alinz** [comment]
@njt1982 I know the pain, unfortunately when you are working with edge technologies which only backed by community you always find yourself in this situation. To me that's the fun of it, figure things out the solutions and understand the concepts. 

One thing I usually do, is commit small things and once I solve it, I do `git diff` to find out why and how. Also you are documenting how you solve the problem by adding more context into the commit message.

every new SDK will break your code, it's not just react-native, swift has gone into many iterations and every iteration breaks the previous one.

**Comment by njt1982** [comment]
IIRC what fixed it for me was to compile and run the main application first, then the extension compiled and ran fine. For me it was caused by project build space being cleaned and the extension being unable to compile as the main project wasn't compiled. I *think* ;) 

@adrianotadao I know what you mean. Sometimes a task which should seem simple snowballs for the most frustrating and obscure reason... However, equally, React Native has let me build my app much more quickly than it would have taken to do it directly in xcode and I have got the added benefit of (in theory) being able to run it with very few changes on Android too.

**Comment by adrianotadao** [comment]
I entirely agree with both of you guys. hehehe I don't hate react-native. I like it, is better than write native code ( a thing that I already did) but, if for instance, the product owner, knows what is react-native, he will think that all things that we will create will be very easy and quick. So, when you have some these problems, the company starts to think that you are unable to do the job and if you gather it with the unknown problem, you start to live a stressful day. 

That's my point. React and react native are nice! I don't like Xcode. hahahaha I need to say: I H-A-T-E Xcode...

**Comment by Faolain** [comment]
If it helps at all guys I fixed this issue by including in my header search paths for the files that were missing these files:

$(SRCROOT)/../../../node_module/React
$(SRCROOT)/../../../node_modules/react-native/React

**Comment by adrianomarquess** [comment]
Same problem in `react-native 0.60.4`

**Comment by RamashishTomar** [comment]
> Same problem in `react-native 0.60.4`

how do you fix it

**Comment by duguodong258** [comment]
same problem in react-native0.61.5
