### ISSUE TITLE
Use with Pods (firebase)

### ISSUE THREAD

**Issue by marcoizzo** [alinz/react-native-share-extension#79]
Hi guys,

thanks for this component.

I'm trying to implement a share extension with a firebase-based app. So I have created a pod file and generated a .xcworkspace project.

I followed all installation tutorial and all same ok, but when I try to launch the extension Xcode console says:

`RNFirebase core module was not found natively on iOS, ensure you have correctly included the RNFirebase pod in your projects 'Podfile' and have run 'pod install'.`

This is my pod file:

```
target 'Together' do
  # Pods for Together
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'

  pod "QBImagePickerController"
  
end

target 'TogetherShareEx' do

  # Pods for TogetherShareEx
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

end
```

And this my TogetherShareEx.m

```
#import <Foundation/Foundation.h>
#import "ReactNativeShareExtension.h"
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLog.h>
#import <Firebase.h>

@interface TogetherShareEx : ReactNativeShareExtension
@end

@implementation TogetherShareEx

RCT_EXPORT_MODULE();

- (UIView*) shareView {
  
  NSURL *jsCodeLocation;
  
  [FIRApp configure];
  
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"TogetherShareEx"
                                               initialProperties:nil
                                                   launchOptions:nil];
  rootView.backgroundColor = nil;
    
  return rootView;
}

@end
```

I'm also:
- added '$(inherited)' in Other Linker Flags
- added '$(SRCROOT)/../node_modules/react-native-firebase/ios/RNFirebase' in Header Search Paths

Any idea? Thanks

**Comment by dolphinflow86** [comment]
Same issue here.

**Comment by alexkuttig** [comment]
Did you include the RNFirebase Project in your extension's build target Link Binary With Libraries? It seems like Firebase is installed correctly but you native RNFirebase Project is missing...

**Comment by marcoizzo** [comment]
I've solved with the creation an app group between the app and the extension

**Comment by BigPun86** [comment]
@marcoizzo can you explain me exactly what you mean? I am not really sure how to do this :)

**Comment by marcoizzo** [comment]
@BigPun86 you have to create an app group. To do this:
1. Click on you project name under navigator
2. Click on your target > Capabilities tab > Enable App Groups
3. Do same operations with app extension target

Then add linked framework and libraries required (libRNFirebase.h) under general tab

I hope this useful :)

**Comment by BigPun86** [comment]
@marcoizzo Unfortunately it didn´t help. But thanks for your explanation. I am using Crashlytics aas well in my pods. I tried to add both libRNFirebase & lib..Crashlytics. I still receive the errors and it wont build my project. I f i remove crashlytics and firebase as linked libraries it will build, but then the app hangs as soon as i share something (URL or Image). Any ideas how to fix that?

**Comment by marcoizzo** [comment]
@BigPun86 what's the error during building?

**Comment by BigPun86** [comment]
@marcoizzo this is the error i am getting: 

<img width="547" alt="screen shot 2018-03-13 at 15 12 53" src="https://user-images.githubusercontent.com/7880624/37346968-12f883e4-26d1-11e8-9ba0-b615846bfcde.png">

This is how my PodFile looks like:

`# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SomeApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SomeApp
  pod 'FirebaseMessaging'
  pod 'Fabric'
  pod 'Crashlytics'

  target 'SomeAppShare' do
    inherit! :search_paths
    # Pods for SomeAppShare
    pod 'FirebaseMessaging'
    pod 'Fabric'
    pod 'Crashlytics'
  end

  target 'SomeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

`

**Comment by marcoizzo** [comment]
@BigPun86 Do you have added `-ObjC` and `-lc++` as linker flags?

**Comment by BigPun86** [comment]
@marcoizzo i added it to the Share Target, yes.

**Comment by marcoizzo** [comment]
@BigPun86 mmm... it seem that the problem is Fabric, but I have never used it so I don't know... Try to remove it in your extension to understand if really crashlytics is the issue

**Comment by BigPun86** [comment]
@marcoizzo now i am getting some React related issues. Maybe u can show me how you have set up your Header Search Path?

This is how mine looks right now: 

<img width="605" alt="screen shot 2018-03-13 at 15 23 46" src="https://user-images.githubusercontent.com/7880624/37347634-92ae610c-26d2-11e8-8736-331260ec8c0a.png">

**Comment by marcoizzo** [comment]
This is mine 
<img width="499" alt="schermata 2018-03-13 alle 15 27 24" src="https://user-images.githubusercontent.com/13518657/37347905-30ce6c24-26d3-11e8-820e-c662b7a1cda1.png">

**Comment by BigPun86** [comment]
@marcoizzo many thanks, i will check it. So actually your Header Search stuff is exactly the same as the one you use for your main target app?

**Comment by marcoizzo** [comment]
@BigPun86  Yep!

**Comment by daviswhitehead** [comment]
@marcoizzo Any more information you can share on your successful setup? I would really appreciate any help you can give towards adding rnfirebase!

I've previously got the share extension working without rnfirebase. Below is some information about my attempt to integrate rnfirebase.

**Share Extension**
ShareExtension.m
![image](https://user-images.githubusercontent.com/8632165/38780531-e6f177bc-40a5-11e8-9dec-38d2ea8314c7.png)

Header Search Paths
![image](https://user-images.githubusercontent.com/8632165/38780486-48484898-40a5-11e8-9dda-970d3ebebff8.png)

Linked Frameworks and Libraries
![image](https://user-images.githubusercontent.com/8632165/38780491-5ba3214c-40a5-11e8-8b4d-a2d8f897f9db.png)

**Main App**
Header Search Paths
![image](https://user-images.githubusercontent.com/8632165/38780502-87dcdfc8-40a5-11e8-9bb6-921a2cbe27d2.png)

Linked Frameworks and Libraries
![image](https://user-images.githubusercontent.com/8632165/38780506-93f1efb0-40a5-11e8-9e4d-e6a5dd56d2d7.png)

**Podfile**
![image](https://user-images.githubusercontent.com/8632165/38780516-b83c374a-40a5-11e8-93a2-42fbc8689248.png)

**Comment by BigPun86** [comment]
@daviswhitehead could you atleast build without issues, or does this already fail?

**Comment by daviswhitehead** [comment]
I can build successfully without trying to integrate rnfirebase. But when I do, I get the following error, which I believe you were seeing as well right @BigPun86 ?
![image](https://user-images.githubusercontent.com/8632165/38783606-3acfbc5a-40d2-11e8-8d8a-f4d95bfc9c70.png)

**Comment by BigPun86** [comment]
@daviswhitehead yeah, i had exactly the same issue. i cant remember what i have done which fixed it...but i think it was enabling AppGroups, maybe you can just try that. If not i hope my setup will help you: 

Linked Libraries and Header Search Path setup of the main App:
<img width="978" alt="screen shot 2018-04-15 at 23 31 10" src="https://user-images.githubusercontent.com/7880624/38783643-50deedee-4105-11e8-8563-c481e5ba5ff3.png">

<img width="670" alt="screen shot 2018-04-15 at 23 31 01" src="https://user-images.githubusercontent.com/7880624/38783648-6604d95e-4105-11e8-95af-9825d1271178.png">

Linked Libraries and Header Search Path setup of the Share Extension:
<img width="676" alt="screen shot 2018-04-15 at 23 30 51" src="https://user-images.githubusercontent.com/7880624/38783655-773b8f38-4105-11e8-8c0e-1a2d608ff5a4.png">
<img width="966" alt="screen shot 2018-04-15 at 23 30 29" src="https://user-images.githubusercontent.com/7880624/38783656-776a5fac-4105-11e8-93a3-74b3f27da68b.png">

**Comment by daviswhitehead** [comment]
@BigPun86 what does your appgroup look like? does this look correct to you? (both the main app and extension look the same)

![image](https://user-images.githubusercontent.com/8632165/38783831-faa1843e-40d5-11e8-9a46-54a0982f7527.png)

**Comment by daviswhitehead** [comment]
I'm getting the same error regardless of if I have App Groups on or off. Any ideas?

**Comment by BigPun86** [comment]
@daviswhitehead yes, but you have to enable it for both, the ShareExtension & the Main App.

**Comment by daviswhitehead** [comment]
Yep I've enabled for both and am getting the same error.

**Comment by BigPun86** [comment]
@daviswhitehead did you run pod install & react-native link after your changes too?

**Comment by daviswhitehead** [comment]
Unfortunately, yes I have and am still on that same error.

**Comment by daviswhitehead** [comment]
I was able to get the firebase pods linked by removing all pods under the extension and adding the line `inherit! :complete`.
However, the extension is now failing at `[FIRApp configure];` in the ShareExtension.m file. Upon debugging, my thread get's killed
![image](https://user-images.githubusercontent.com/8632165/38815480-0655be26-4162-11e8-9a88-a2a7d2bcf8f9.png)
and I get the following output `Message from debugger: Terminated due to signal 6`

Any ideas @BigPun86 or @marcoizzo ?

**Comment by emilefleming** [comment]
@daviswhitehead I'm experiencing the same linker error you were at first:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRMessaging", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseMessaging.o)
  "_OBJC_CLASS_$_FIRTransactionResult", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseDatabase.o)
  "_OBJC_CLASS_$_FIRDatabase", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseDatabase.o)
  "_OBJC_CLASS_$_FIRAnalyticsConfiguration", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAnalytics.o)
  "_OBJC_CLASS_$_FIRAnalytics", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAnalytics.o)
  "_OBJC_CLASS_$_FIRGitHubAuthProvider", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
  "_OBJC_CLASS_$_FIREmailAuthProvider", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
  "_OBJC_CLASS_$_FIRFacebookAuthProvider", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
  "_OBJC_CLASS_$_FIRActionCodeSettings", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
  "_OBJC_CLASS_$_FIRInstanceID", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseInstanceId.o)
      objc-class-ref in libRNFirebase.a(RNFirebaseMessaging.o)
  "_OBJC_CLASS_$_FIRAuth", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
  "_OBJC_CLASS_$_FIRTwitterAuthProvider", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
  "_OBJC_CLASS_$_FIROptions", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebase.o)
  "_OBJC_CLASS_$_FIROAuthProvider", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
  "_OBJC_CLASS_$_FIRApp", referenced from:
      objc-class-ref in ShareExtension.o
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
      objc-class-ref in libRNFirebase.a(RNFirebase.o)
      objc-class-ref in libRNFirebase.a(RNFirebaseUtil.o)
  "_OBJC_CLASS_$_FIRPhoneAuthProvider", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
  "_OBJC_CLASS_$_FIRGoogleAuthProvider", referenced from:
      objc-class-ref in libRNFirebase.a(RNFirebaseAuth.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Do you recall if there were any steps you took to resolve it that weren't mentioned in this thread?

The extension portion of my podfile looks like this:

```
target 'ShareExtension' do
  inherit! :complete
end
```

Linker flags are set correctly.

In my header search paths for the extension I have 

```
$(inherited)
$(SRCROOT)/../node_modules/react-native-firebase/ios/RNFirebase
$(SRCROOT)/../node_modules/react-native-share-extension/ios
```

Under Build Phases > Link Binary with Libraries I have `libRNFirebase.a` and `libPods-ShareExtension.a`

Does anything else come to mind that I might try?

Interestingly enough when I remove firebase I am able to build but get a runtime error related to firebase, even if I don't import it in ShareExtension.m

**Comment by AndrewHenderson** [comment]
For anyone struggling with this issue. After following the standard installation instructions, make sure you do the following:

1) Link `libRNFirebase.a` in your Extension's Build Phases.
Also, make sure that `libPods-{YOUR_EXTENSION_NAME}.a` is linked as well.
2) Set the GoogleService-Info.plist target for both your main app and your share extension in the right panel.
3) In your share extension's Build Settings > Other Linker Flags, make sure you add $(inherited)
4) **In your Share Extension `.m` file, make sure you import Firebase and configure it there as well!**
```
#import <Firebase.h>
- (UIView*) shareView {
  NSURL *jsCodeLocation;
  [FIRApp configure];
  …
}

**Comment by i25878427** [comment]
@AndrewHenderson Do you know if it is possible to authenticate with firebase from the main app and some how pass the authentication to the share extension? (I don't want to ask the user to do login again)

**Comment by AndrewHenderson** [comment]
@i25878427 Use [react-native-shared-group-preferences](https://www.npmjs.com/package/react-native-shared-group-preferences). For iOS you'll need to create an "App Group" and give both your app and the extension permission. This has to be done in Xcode. The install steps should cover everything.

**Comment by i25878427** [comment]
@AndrewHenderson Thanks for the help :-). I already have "App Group" installed and I was able to share data between the main app and the share extension.

Maybe my question is more firebase related. I don't know what should I share with the share extension from the main app to make the share extension authenticate with firebase, so I can read/write to firebase database.

**Comment by AndrewHenderson** [comment]
@i25878427 I've found that the Share extension has its own scope and any modules have separate instances — so your Firebase instance would probably have to be initialized for both.

The only data I've been able to share is storing strings in the App Group.

You're better off asking these questions in https://github.com/invertase/react-native-firebase. They also have their own channel on Discord. Good luck! 😄

**Comment by i25878427** [comment]
@AndrewHenderson Thanks! I will try using their channel :-)

**Comment by daviswhitehead** [comment]
not totally sure how this works technically, but I was able to authenticate with firestore through the share extension in the same way I do within my main app. Not sure if it's any different for firebase but would guess not.

`this.authSubscription = firebase.auth().onAuthStateChanged((user) => {
      this.setState((previousState) => {
        return {
          ...previousState,
          loading: false,
          user: user,
        }
      })
    });`

**Comment by kdepp** [comment]
> In your share extension's Build Settings > Other Linker Flags, make sure you add $(inherited)

Adding `${inherited}` fixed my problem.  Thanks for your info, @AndrewHenderson
